### ISSUE TITLE
Открыть доступ к IEsiaEnvironment

### ISSUE THREAD

**Issue by TechnoBerry** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#1]
На текущий момент интерфейс `IEsiaEnvironment` и его имплементации имеют `internal` модификатор доступа. Это приводит к тому, что для запросов без использования `IEsiaRestService` требуется самостоятельно реализовывать логику по выбору используемого хоста ЕСИА. Было бы здорово, если бы можно было переиспользовать имеющийся `IEsiaEnvironment`.

**Comment by vladdy-moses** [comment]
Добрый день. Правки сделали, в самое ближайшее время выложим в NuGet.
