### ISSUE TITLE
Маленькая неточность в документации

### ISSUE THREAD

**Issue by planar74** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#12]
Команда для создания ключа должна выглядеть так

openssl req -x509 -newkey gost2012_256 -pkeyopt paramset:A -nodes -keyout esia.key -out esia.pem -days 3650 **-engine gost**

Без выделенного параметра выводит ошибку 

`Unknown algorithm gost2012_256`

Этот же параметр надо добавить и при создании сертификата

**Comment by vladdy-moses** [comment]
Добрый день!
Прошу прощения за долгое реагирование на issue.
Документацию обновил, команды проверил, спасибо.
