### ISSUE TITLE
Кастомные SecurityTokenValidator и OpenIdConnectHandler

### ISSUE THREAD

**Issue by RPogodin** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#14]
Владислав, здравствуйте!

Появилась необходимость использовать кастомные SecurityTokenValidator и OpenIdConnectHandler.

Закинул пулл-реквест: https://github.com/AISGorod/AISGorod.AspNetCore.Authentication.Esia/pull/13

Спасибо!

**Comment by vladdy-moses** [comment]
Добрый день.
Прошу прощения за то, что так долго реагировал на issue.
PR влил, изменения появятся в nuget в ближайший день.
