### ISSUE TITLE
Cookie policy with Chrome

### ISSUE THREAD

**Issue by umbruxo** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#15]
не могу понять никак, какие настройки нужно указать в кукис аутентификации, чтобы в хроме заработало.

Вот так не работает, хотя Хром говорит, что должно быть указано SameSiteMode.None и CookieSecurePolicy.Always;
Можете подсказать?

services.AddAuthentication(options =>
                {
                    options.DefaultScheme = "Cookies";
                    options.DefaultChallengeScheme = "Esia";
                })
                .AddCookie("Cookies", options =>
                {
                    options.Cookie.Name = "TestLinuxWebApp.Cookie";
                    options.ExpireTimeSpan = TimeSpan.FromMinutes(30);
                    //вероятно это нужно для новых Хром)
                    options.Cookie.SameSite = (SameSiteMode)@Configuration.GetSection("Cookie").GetValue<int>("SameSite"); //SameSiteMode.None
                    options.Cookie.SecurePolicy = (CookieSecurePolicy)@Configuration.GetSection("Cookie").GetValue<int>("SecurePolicy"); //CookieSecurePolicy.Always;
                })
                .AddEsia("Esia", options =>
                {
                    options.Environment = EsiaEnvironmentType.Production;
                    options.Mnemonic = "ODOMSU43";                                         
                    //options.SignOutScheme = "Cookies";
                    options.Scope = new[] { "openid","fullname"}; //узнать что было в заявке на регистрацию системы
                    options.SaveTokens = true;

                });

**Comment by anderr225** [comment]
Приветствую, столкнулся с аналогичной проблемой. Хром просто не выставляет куки `Nonce`и `Correlation` из-за того, что у них атрибут `SameSite` выставлен в `None`, а атрибут `Secure` не выставлен. Если для них атрибут `SameSite` выставить в `Lax`, проблема решается. Однако, это не исправить через конфигурацию `.AddCookie` как у вас в примере, потому что в этом месте другие куки настраиваются. Куки `Nonce` и `Correlation` без обновления библиотеки настроить не получится. В библиотеки за эту настройку отвечает класс `OpenIdConnectOptionsBuilder`, а точнее его метод `BuildAction`. Если в конце этого метода добавить строчки `options.NonceCookie.SameSite = SameSiteMode.Lax;` и `options.CorrelationCookie.SameSite = SameSiteMode.Lax;` проблема решится. Будет время, отправлю пр с изменениями. Без обновления библиотеки я не нашел как решить данную проблему.

**Comment by umbruxo** [comment]
Попробую.

**Comment by planar74** [comment]
> Если в конце этого метода добавить строчки `options.NonceCookie.SameSite = SameSiteMode.Lax;` и `options.CorrelationCookie.SameSite = SameSiteMode.Lax;` проблема решится.

У меня она не решилась подобным образом, получилось только через

`               options.NonceCookie.SameSite = SameSiteMode.None;
                options.CorrelationCookie.SameSite= SameSiteMode.None;
                options.NonceCookie.SecurePolicy = CookieSecurePolicy.Always; ;
                options.CorrelationCookie.SecurePolicy = CookieSecurePolicy.Always;`

В конце метода BuildAction
