### ISSUE TITLE
Redirect after logout

### ISSUE THREAD

**Issue by umbruxo** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#3]
Подскажите, пжлста, как организовать редирект после выхода из ЕСИА на страницу приложения, а не на страницу входа ЕСИА?

**Comment by vladdy-moses** [comment]
Добрый день. Насколько мне известно, при регистрации ИС указывается список доменов приложения.
Если перенаправление в выход из ЕСИА было произведено из этих доменов, то пользователь впоследствии перекидывается в приложение, иначе остаётся в ЕСИА.
