### ISSUE TITLE
Не работает sample-приложение

### ISSUE THREAD

**Issue by vladarval** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#4]
При изменении Startup.cs приложение-пример по-прежнему не работает.

**Comment by vladdy-moses** [comment]
Добрый день.
Можете подробнее описать, в чём заключается ошибка?

**Comment by sadam-agashirinov** [comment]
Доброго времени суток. У меня аналогичная проблема, не работает sample - приложение.
При запуске приложения сразу после скачивания, без предварительной настройки, запускается браузер и выдает ошибку 
"Ошибка при установлении защищённого соединения. При соединении с localhost:5000 произошла ошибка. PR_CONNECT_RESET_ERROR".
В окне "Средства диагностики" нет сообщений о каких-либо событиях или ошибках. 
Поставил точки останова в классе Startup.cs и Program.cs, безрезультатно. Приложение в этих точках не останавливается. 
Использую 
1. VS2019 Professional версии 16.5.0
2. Windows 10 Pro

![Безымянный](https://user-images.githubusercontent.com/23429381/77416016-65678980-6dd4-11ea-9a11-ed7f1c4658a9.png)

**Comment by vladdy-moses** [comment]
> Доброго времени суток. У меня аналогичная проблема, не работает sample - приложение.

Здравствуйте!
Попробуйте запустить приложение при помощи профиля "SelfHost" (выбирается через стрелку вниз на кнопке "Run").
В этом случае при старте приложения откроется консоль, в которой возможно будет указана какая-либо ошибка.

Проблема похожа на то, что браузер заблокировал самоподписанный сертификат, который необходим для https-соединения.

В качестве альтернативного решения проблемы попробуйте открыть файл `Properties/launchSettings.json`, удалить оттуда строку `"sslPort": 5000` и переключиться обратно на профиль "IIS Express".
Либо в том же файле `"applicationUrl": "https://localhost:5000",` можно исправить на `"applicationUrl": "http://localhost:5001",` для SelfHost.
Тогда сайт будет открываться как http://localhost:5001, и ошибки установки соединения не должно возникать.

**Comment by sadam-agashirinov** [comment]
Спасибо. Вариант с запуском при помощи профиля "SelfHost" помог.
При попытке авторизации выдало сообщение 
"OpenIdConnectProtocolException: Message contains error: 'unauthorized_client', error_description: 'ESIA-007005: The client is not authorized to request an access token using this method.', error_uri: 'error_uri is null'."

Видимо что-то с правами доступа. Будем разбираться

**Comment by slemvs** [comment]
> Спасибо. Вариант с запуском при помощи профиля "SelfHost" помог.
> При попытке авторизации выдало сообщение
> "OpenIdConnectProtocolException: Message contains error: 'unauthorized_client', error_description: 'ESIA-007005: The client is not authorized to request an access token using this method.', error_uri: 'error_uri is null'."
> 
> Видимо что-то с правами доступа. Будем разбираться

Подскажите, пожалуйста, у вас получилось разобраться с проблемой?

**Comment by sadam-agashirinov** [comment]
> 
> 
> > Спасибо. Вариант с запуском при помощи профиля "SelfHost" помог.
> > При попытке авторизации выдало сообщение
> > "OpenIdConnectProtocolException: Message contains error: 'unauthorized_client', error_description: 'ESIA-007005: The client is not authorized to request an access token using this method.', error_uri: 'error_uri is null'."
> > Видимо что-то с правами доступа. Будем разбираться
> 
> Подскажите, пожалуйста, у вас получилось разобраться с проблемой?

1. При регистрации в ЕСИА нужно подключить scope openid
2. У меня ошибка была из-за того, что я не правильно подписывал данные. Об этом мне сказали, когда я отправил в ЕСИА запросы и ответы предшествующие ошибке. Ошибку исправил, сейчас запросы проходят нормально.
