### ISSUE TITLE
Получение сертификатов в виде файлов после создания их в линуксе.

### ISSUE THREAD

**Issue by sadam-agashirinov** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#7]
Доброго времени суток! 
Как после создания сертификатов в линуксе заполучить их в виде файлов у себя на винде?

**Comment by vladdy-moses** [comment]
Добрый день!

Если Вы используете WSL (например, установили ubuntu через магазин приложений в windows и сгенерировали сертификаты там), то все диски windows примонтированы в директории `/mnt/`.
Например, `/mnt/c/` - аналог C:\, `/mnt/d` - аналог D:\ и т.д.
В этом случае достаточно скопировать сгенерированные файлы при помощи команды `cp путь-до-файла-в-linux /mnt/путь-в-windows`.
Более подробно про WSL можно узнать тут: https://docs.microsoft.com/ru-ru/windows/wsl/faq

Также мы разработали небольшую инструкцию, как можно использовать openssl с ГОСТ напрямую в Windows.
Если интересно, могу скинуть. Для тестирования она подойдёт.
