### ISSUE TITLE
Вопрос о схеме взаимодействия

### ISSUE THREAD

**Issue by slemvs** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#8]
Добрый день,
Подскажите, пожалуйста, если требуется подключить ЕСИА в качестве внешнего oidc провайдера на собственном is4 сервере, можно ли для этого использовать данную библиотеку и какой порядок действий в настройке должен быть? Т.е. основное веб-приложение использует собственный is4 и должно давать возможность авторизации через ЕСИА.

**Comment by vladdy-moses** [comment]
Добрый день.
Прошу прощения за долгий ответ.
Да, такой механизм возможен и реализован, например, тут: https://auth.aisgorod.ru/
В течение дня напишу более подробно, как мы добились такого поведения.

**Comment by vladdy-moses** [comment]
В _Startup.cs_ в методе `ConfigureServices(IServiceCollection services)` вызывается `services.AddAuthentication()`.
Если в качестве внешнего поставщика используется только ЕСИА, то можно сразу написать что-то наподобие `services.AddAuthentication().AddEsia(....)`.

Внутри AddEsia достаточно настроить Environment (например, `options.Environment = EsiaEnvironmentType.Production;`), Mnemonic (мнемоника системы, которая указывалась на технологическом портале ЕСИА) и Scope (набор ресурсов, к которым у Вашей ИС есть доступ).

После этого необходимо настроить _IEsiaSigner_, чтобы определить алгоритм подписи запросов при помощи ГОСТ (сейчас в .net нет стандартной реализации хеширования и подписи по ГОСТ, поэтому приходится изобретать собственный велосипед).
У нас это настроено как  `services.AddSingleton<IEsiaSigner, Services.OpensslEsiaSigner>();` (подпись при помощи OpenSSL взята из этого репозитория из проекта с примером).

Этого достаточно, чтобы подключить ЕСИА как внешний oidc-провайдер.

Как можно заметить, алгоритм никак не зависит от наличия/отсутствия is4.
Единственное, о чём надо не забыть - это передавать ReturnUrl при входе через внешнего поставщика.  Это связано с тем, что is4 именно по наличию ReturnUrl определяет контекст входа (можете посмотреть на `IIdentityServerInteractionService` для более подробной информации).

Надеюсь, что смог Вам помочь.
Если остаются какие-либо вопросы, буду рад ответить.
