### ISSUE TITLE
Дополнительные параметры в запросе

### ISSUE THREAD

**Issue by anderr225** [AISGorod/AISGorod.AspNetCore.Authentication.Esia#9]
Доброго времени суток.

Для интеграции с цифровым профилем, в первом редиректе в ЕСИА требуется указать дополнительный параметр. Сейчас параметры добавляются в классе `EsiaEvents`, который объявлен internal, соответственно возможности это сделать нет. Было бы неплохо добавить такую возможность.

Если нет вопросов к issue могу сам заняться и отправить pr.

**Comment by vladdy-moses** [comment]
Добрый день. Прошу прощения за долгий ответ.
Принял Ваш PR, спасибо!
В течение дня сформирую версию 1.3.0 и выложу в nuget.

**Comment by anderr225** [comment]
Благодарю
